# Config file for gh pages
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ADSA
description: Auto-Downloader and Stat-Analyzer for DCSS 0.11+ (WIP) 
