# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  getcurl:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Prepare curl"
          command: |
            "wget -O \"https://curl.se/download/curl-8.2.1.tar.gz\""
            "tar xf curl-8.2.1.tar.gz"
            "cd curl-8.2.1"
            "./configure --with-gnutls"
            "make"
            "cd .."
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Build"
          command: "g++ -Wall -O2 -std=c++17 -Icurl-8.2.1/include -Lcurl-8.2.1/lib -lcurl -o adsa main.cpp"
      - store_artifacts:
          path: adsa
          destination: adsa
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Tests"
          command: |
            "./adsa -pOexample_output.txt"
      - store_artifacts:
          path: example_output.txt
          destination: example_output.txt

workflows:
  default-workflow:
    jobs:
      - getcurl
      - build:
          requires:
            - getcurl
      - test:
          requires:
            - build
